spring:
  config:
    import: security/application-datasource.yml
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/schema.sql
      data-locations: classpath:sql/data/**/*.sql